# Generated by Django 3.2.6 on 2021-11-08 18:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cursos', '0002_auto_20210809_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='alunos',
            field=models.ManyToManyField(blank=True, related_name='cursos_aluno', to=settings.AUTH_USER_MODEL),
        ),
    ]
